package com.ve.lawyer.utils

class AppConstants {
    companion object{
        val CLIENT_USER_TYPE = "CLIENT_USER_TYPE"
        val LAWYER_USER_TYPE = "LAWYER_USER_TYPE"

        val CATEGORY_LIST_VIEW_INITIAL = "CATEGORY_LIST_VIEW_INITIAL"
        val CATEGORY_LIST_VIEW_ALL = "CATEGORY_LIST_VIEW_ALL"

        val USER_POST_PAGE_SHOWING_FROM = "USER_POST_PAGE_SHOWING_FROM"
        val USER_POST_PAGE_SHOWING_FROM_POST = "USER_POST_PAGE_SHOWING_FROM_DASHBOARD"
        val USER_POST_PAGE_SHOWING_FROM_CATEGORY = "USER_POST_PAGE_SHOWING_FROM_CATEGORY"
    }
}